apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: music-store-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/niranec77/gitops-bootstrap.git
        revision: main
        directories:
          - path: apps/
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/niranec77/gitops-bootstrap.git
        targetRevision: main
        path: apps/{{path.basename}}
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  selector:
    matchLabels:
      region: east

